### ISSUE TITLE
Making MONC output CF-compliant (trac #232)

### ISSUE THREAD

**Issue by leifdenby** [Leeds-MONC/monc#6]
*until we've migrated properly from trac I am copying this issue over manually*

The aim of this ticket is to track the implementation of making output from
MONC CF-compliant. The changes will be available on the branch at
https://code.metoffice.gov.uk/svn/monc/main/branches/dev/leifdenby/vn0.8_cf-compliance.

Proposed changes:

1. All fields published by a MONC component may now ''optionally'' define:
    1. The ''standard name'' of the field. These should follow the names given in
    the CF-compliance Standard Names table:
    http://cfconventions.org/standard-names.html
    2. The ''units'' of the field, following the UDUNITS convention. Can easily be
    checked by the [https://pypi.python.org/pypi/cfunits/ cfunits] python
    package
    3. A ''long_name'' of the field. These are more descriptive and can be
    anything, but are used by quite a lot of analysis packages for labelling axes

   To add `units` and `long_name` for example for the `ql_max` diagnostic, the
   following lines would be added to `field_information_retrieval_callback` of
   `monc/components/diagnostics/src/diagnostics.F90`:

```
subroutine field_information_retrieval_callback(current_state, name, field_information)
    ...
    if (name .eq. "qlmax_local") then
       field_information%units = 'kg/kg'
       field_information%long_name = "column maximum liquid water specific mass"
    endif
    ...
end subroutine field_information_retrieval_callback
   ```

2. `units`, `long_name` and `standard_name` will "propagate down" when MPI
  reductions are done on MONC IO server, so that chained MPI reductions (defined
  in IO server XML configuration file) will inherit these variables from the component field which was published from a MONC component. '''NB''': This solution is not ideal since one component field could in theory be used to define multiple different outputs (by using different MPI reductions), but unless these MPI reductions are abstracted away this can't be solved at present (see below).

3. New 3D component fields to define the total pressure and potential
   temperature (named `total_pressure` and `total_theta`), so that these may be
   stored with standard names in output and aid analysis (currently the variables
   `pressure` and `theta` contain the perturbations from the anelastic reference
   state)

4. Auto-definition of shapes and sizes in MONC output based on shape and size
   of arrays received from MONCs, this would mean that expressions like `size="zn,y,x"` are no longer necessary in the MONC IO XML server configuration file.

5. Inclusion of '''all''' grid positions in MONC output '''by default'''. Currently
   only `zn` is included, CF-compliance requires that grid positions are defined
   in output. This will be achieved by adding new variables in the output NetCDF
   file called `x`, `y`, `xn`, `yn` and `z` respectively.
6. Definition of `standard_name`, `units` and `long_name` for globally available fields (e.g. `u`, `v`, `w`, `th`, `x`, etc) where applicable to ensure  CF-compliance when these fields are included in MONC output.

Future work:

- Work out if `type` and `collective_type` in the MONC IO server XML configuration file can be inferred from data received from the MONCs too.

- Add validation of units entered by using the Fortran API of the UDUNITS package

- Remove necessity for chaining of MPI commands in IO Server XML configuration file by changing how for example column averaged output is created. The XML configuration file could simply request a variable `ql_column_average` which would be published by a MONC component using a new subroutine which generates and publishes column averages of a given 3D field.

**Comment by leifdenby** [comment]
*copy-paste of comment on trac*

I've made a pull request (referenced above) which contains

1. Changes to introduce meta information to relevant Fortran data types for diagnostic, prognostic and "component" fields

2. Subroutines which provide standard name, long name and units for prognostic fields (https://github.com/leifdenby/monc/tree/cf-compliance-refactor/model_core/src/state.F90#L92)

3. Functionality to communicate field information from MONCs to IO server, includes changes to MPI datatype used for communication

4. Functionality to iterate over "activities" for each active diagnostic field and build units and long name (description) from activities depending on the type of activity. Because the activities each contribute the "long name" description these leads to `long_name` like `sum of per-MONC sum of per-column liquid-water path divided by domain xy-cell-count`, and therefore I have also introduced a string-mapping which changes recognises some common patterns, and turns this example into `domain-wide mean of per-column liquid-water path`.  '''NB''': For arithmetic operations the routine doesn't currently use the "equation tree" to work out how fields that are used are combined, but the examples of fields I have looked at only have products of component fields

5. Actually setting the meta information in the NetCDF output.

6. Changes to a lot IO XML configuration file for a lot of fields and introduction of the meta information into the component field's `field_information_retrieval_callback`

## TODO

- [ ] Implement a routine similar to `build_equation_tree` (http://homepages.see.leeds.ac.uk/~earlcd/MONC/doc/releases/vn0.8/namespacearithmetic__operator__mod.html#a24bf0ea213d6e08249db2b727e2ca875) to work out how the units of "required fields" for an arithmetic operation should be combined

- [ ] Work out what to do with fields that are in defined in the output writers but don't have a matching definition in the _diagnostics defintions_

- [ ] enter meta information for remaining component fields (I haven't done any which are based on products of diagnostic fields since I'm not sure what the loops that calculate these are actually doing) 

- [ ] work out how to provide meta information for `q_vapour` and `q_liquid_water`.
  Because the names of these fields are set at runtime, but aren't available as
  component fields as with other diagnostic fields, it's a bit harder to do
  this. I am guessing this needs to be added to the casim component

### Questions

1. What does the component field `uu_total_local` actually contain?

2. Are `reducelocal` operations always "vertical" reductions in that they apply
  along the z-direction?

3. `thref` exists as both a diagnostic field computed via `thref_local` in
  `components/profile_diagnostics/src/profile_diagnostics.F90` and directly as
  a "globally sendable field" in `components/iobridge/src/iobridge.F90`.
  I think it should only be available as a globally sendable field since it
  doesn't change over the simulation. Similarly `thinit`, `rho`, `rhon`,
  `prefn` are currently in _profile diangnostics_, but they are unchanged
  during the simulation evolution, I suggest we move to the _iobridge_.

4. what does the equation for `lwp_var` in `components/scalar_diagnostics/src/scalar_diagnostics.F90` mean?

    `<operator name="arithmetic" result="lwp_var_local" equation="(lwp_local-10)"/>`

5. the units of `lathf_mean`, `lathf_max` etc is `m` in
  `io/io_cfg_files/scalar_fields.xml`, is this correct? I was expecting it to
  be `W/m^2`

Also, the routines are very verbal in that warnings are issued if any used component fields do not have "units" or "long_name" set. This is to encourage adding these if new component fields are added.

I've added examples for the output of `ncdump -h` for the BOMEX with examples before and after these changes.

I'm going to focus on defining the grid next in the output next. This is required by CF-conventions, but also the scalar fields aren't all defined on the right grid points right now (u, v, w should each be staggered at interface for instance). This will involve automatically defining the shape fields being written.
